version: "3.8"

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: yolo-client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - app-net
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: yolo-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/yolo
    networks:
      - app-net
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: yolo-mongo
    ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  app-mongo-data: