apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: yolo-app
spec:
  type: ClusterIP
  ports:
    - port: 5000         # Service port exposed inside the cluster
      targetPort: 8000   # Container port the backend app listens on
  selector:
    app: yolo-app        # Matches the label used in backend deployment pods
